name: CI
on:
  push:
    branches:
      - main
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
jobs:
  test-plugin:
    name: Test plugin
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - SummerRest
        unityVersion:
          - 2022.3.1f1
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
      # Cache
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-${{ hashFiles(matrix.projectPath) }}
            Library-
      # Test
      - uses: game-ci/unity-test-runner@v4
        id: tests
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          artifactsPath: UnityTests-${{ matrix.unityVersion }}
      # Upload test results
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: UnityTests-${{ matrix.unityVersion }}
          path: ${{ steps.tests.outputs.artifactsPath }}

  export-plugin:
    name: Export plugin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projectPath:
          - SummerRest
        unityVersion:
          - 2022.3.1f1
        targetPlatform:
          - StandaloneLinux64 # Build a Linux 64-bit standalone
        include:
          - projectPath: SummerRest
            packagePath: Assets/Plugins/SummerRest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
      # Cache
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-${{ hashFiles(matrix.projectPath) }}
            Library-
      # Export custom packages (not build)
      - name: Export packages
        uses: game-ci/unity-builder@v4
        with:
          buildMethod: Editor.ExportPackage.Export
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: -packagePath "${{ matrix.packagePath }}" -outputPath "Build/${{ matrix.projectPath }}.${{ matrix.unityVersion }}.unitypackage"
      # Upload packages
      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.projectPath }}.unitypackage
          path: ${{ matrix.projectPath }}/Build/${{ matrix.projectPath }}.${{ matrix.unityVersion }}.unitypackage

  export-sample:
    name: Export sample project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
      # Upload packages
      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: SampleRestSample.unitypackage
          path: SummerRestSample/

  test-generator:
    name: Test source generator
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [ '7.0.x' ]
        projectPath:
          - Generator
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: actions/cache@v3
        name: Cache NuGet packages
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Install dependencies
        working-directory: ${{ matrix.projectPath }}
        run: dotnet restore
      - name: Test with dotnet
        working-directory: ${{ matrix.projectPath }}
        run: dotnet test --logger trx --results-directory "../GeneratorTests-${{ matrix.dotnet-version }}"
      - name: Upload dotnet test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: GeneratorTests-${{ matrix.dotnet-version }}
          path: GeneratorTests-${{ matrix.dotnet-version }}/
